// ============= SMART CUT EDUCATION - DONNEES DE DEMONSTRATION =============
// Ces objets suivent exactement le schema Firestore documente dans
// EDUCATION_DATA_ARCHITECTURE.md (mêmes noms de champs que
// educationCategories / educationSchools / educationPrograms), afin que
// education-demo-source.js les fasse passer par les MÊMES fonctions de
// normalisation (education-normalize.js) que les vraies donnees Firestore
// lues par education-repository.js. Aucune adresse precise, aucun numero de
// telephone, aucun agrement, aucune certification et aucune note ou avis ne
// sont inventes. isDemo:true partout ; ce module n'est utilise qu'en mode
// demonstration explicite (?demo=1), jamais mélangé au catalogue normal.

const DEMO_CREATED_AT = '2026-06-01T00:00:00.000Z';
const DEMO_PUBLISHED_AT = '2026-06-05T00:00:00.000Z';

export const RAW_CATEGORIES = [
  { id: 'tech', name: 'Informatique et technologie', description: 'Programmation, cybersécurité et outils numériques.', icon: 'fa-laptop-code', image: null, order: 1, isActive: true },
  { id: 'gestion', name: 'Gestion et entrepreneuriat', description: 'Comptabilité, marketing et pilotage de petites structures.', icon: 'fa-briefcase', image: null, order: 2, isActive: true },
  { id: 'langues', name: 'Langues', description: 'Communication orale et écrite en contexte professionnel.', icon: 'fa-language', image: null, order: 3, isActive: true },
  { id: 'sante', name: 'Santé', description: 'Métiers du soin et de l’accompagnement.', icon: 'fa-briefcase-medical', image: null, order: 4, isActive: true },
  { id: 'metiers', name: 'Métiers techniques', description: 'Électricité, plomberie et maintenance.', icon: 'fa-screwdriver-wrench', image: null, order: 5, isActive: true },
  { id: 'arts', name: 'Arts et création', description: 'Illustration, design et création numérique.', icon: 'fa-palette', image: null, order: 6, isActive: true }
];

function demoVerification() {
  return {
    status: 'unverified',
    label: 'Établissement non vérifié — profil de démonstration',
    checkedItems: [],
    reviewedAt: null,
    reviewedBy: null
  };
}

export const RAW_SCHOOLS = [
  {
    id: 'demo-school-1',
    slug: 'institut-numeritech',
    name: 'Institut NumériTech',
    shortDescription: 'École spécialisée en informatique et en nouvelles technologies, tournée vers les métiers numériques en Haïti.',
    fullDescription: 'Institut NumériTech propose des parcours courts en programmation, cybersécurité et outils numériques, pensés pour des apprenants qui veulent progresser rapidement vers l’emploi ou l’entrepreneuriat en ligne.',
    domains: ['Informatique', 'Technologie'],
    commune: 'Port-au-Prince',
    department: 'Ouest',
    addressLabel: 'Port-au-Prince, Haïti',
    publicContact: 'Contact disponible prochainement via Smart Cut Education',
    coverImage: null,
    logoImage: null,
    publicationStatus: 'published',
    verification: demoVerification(),
    ownerUid: null,
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-school-2',
    slug: 'centre-progestion',
    name: 'Centre ProGestion',
    shortDescription: 'Centre de formation dédié à la gestion, à l’entrepreneuriat et au marketing pour petites structures.',
    fullDescription: 'Le Centre ProGestion accompagne des porteurs de projet et des employés d’entreprises locales avec des formations courtes en gestion, comptabilité simplifiée et marketing digital.',
    domains: ['Gestion', 'Entrepreneuriat'],
    commune: 'Pétion-Ville',
    department: 'Ouest',
    addressLabel: 'Pétion-Ville, Haïti',
    publicContact: 'Contact disponible prochainement via Smart Cut Education',
    coverImage: null,
    logoImage: null,
    publicationStatus: 'published',
    verification: demoVerification(),
    ownerUid: null,
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-school-3',
    slug: 'ecole-langues-plus',
    name: 'École Langues Plus',
    shortDescription: 'École de langues proposant des cours d’anglais et de français professionnel.',
    fullDescription: 'École Langues Plus propose des formations en petits groupes, en présentiel et en ligne, pour progresser rapidement à l’oral comme à l’écrit dans un contexte professionnel.',
    domains: ['Langues'],
    commune: 'Pétion-Ville',
    department: 'Ouest',
    addressLabel: 'Pétion-Ville, Haïti',
    publicContact: 'Contact disponible prochainement via Smart Cut Education',
    coverImage: null,
    logoImage: null,
    publicationStatus: 'published',
    verification: demoVerification(),
    ownerUid: null,
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-school-4',
    slug: 'centre-metiers-technix',
    name: 'Centre de Métiers Technix',
    shortDescription: 'Centre de formation aux métiers techniques : électricité, plomberie et maintenance.',
    fullDescription: 'Le Centre de Métiers Technix forme aux gestes professionnels des métiers techniques, avec des sessions pratiques encadrées par des formateurs expérimentés du secteur.',
    domains: ['Métiers techniques'],
    commune: 'Delmas',
    department: 'Ouest',
    addressLabel: 'Delmas, Haïti',
    publicContact: 'Contact disponible prochainement via Smart Cut Education',
    coverImage: null,
    logoImage: null,
    publicationStatus: 'published',
    verification: demoVerification(),
    ownerUid: null,
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-school-5',
    slug: 'institut-sante-avenir',
    name: 'Institut Santé Avenir',
    shortDescription: 'Institut de formation aux métiers de la santé et du soin.',
    fullDescription: 'Institut Santé Avenir prépare aux fonctions de soin de base avec des modules théoriques et des mises en situation encadrées, en lien avec les besoins des structures de santé locales.',
    domains: ['Santé'],
    commune: 'Cap-Haïtien',
    department: 'Nord',
    addressLabel: 'Cap-Haïtien, Haïti',
    publicContact: 'Contact disponible prochainement via Smart Cut Education',
    coverImage: null,
    logoImage: null,
    publicationStatus: 'published',
    verification: demoVerification(),
    ownerUid: null,
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-school-6',
    slug: 'atelier-creatif-studio',
    name: 'Atelier Créatif Studio',
    shortDescription: 'Studio de formation en ligne dédié à l’illustration et à la création numérique.',
    fullDescription: 'Atelier Créatif Studio propose des formations en ligne pour apprendre l’illustration numérique et les outils graphiques, avec des ateliers en direct pour pratiquer régulièrement.',
    domains: ['Arts et création'],
    commune: 'En ligne',
    department: null,
    addressLabel: 'Formation en ligne',
    publicContact: 'Contact disponible prochainement via Smart Cut Education',
    coverImage: null,
    logoImage: null,
    publicationStatus: 'published',
    verification: demoVerification(),
    ownerUid: null,
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  }
];

function demoCapacity() {
  return { total: null, available: null, displayLabel: 'Places bientôt disponibles' };
}

export const RAW_PROGRAMS = [
  {
    id: 'demo-course-1',
    slug: 'initiation-developpement-web',
    title: 'Initiation au développement web',
    shortDescription: 'Apprenez les bases du HTML, CSS et JavaScript pour créer vos premières pages web.',
    fullDescription: 'Cette formation d’introduction vous fait découvrir la construction d’une page web de A à Z : structure HTML, mise en forme CSS et premières interactions en JavaScript. Elle s’adresse à toute personne curieuse de comprendre comment fonctionne le web, sans expérience préalable requise.',
    categoryId: 'tech',
    schoolId: 'demo-school-1',
    level: 'Débutant',
    modality: 'online',
    commune: null,
    department: null,
    duration: { value: 8, unit: 'weeks' },
    schedule: 'Cours en ligne à votre rythme, avec suivi hebdomadaire',
    prerequisites: 'Aucun prérequis',
    price: { amount: 3500, currency: 'HTG', isOnRequest: false },
    registration: { status: 'open', displayLabel: 'Inscriptions ouvertes toute l’année' },
    capacity: demoCapacity(),
    image: null,
    badge: null,
    publicationStatus: 'published',
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-course-2',
    slug: 'gestion-petite-entreprise',
    title: 'Gestion de petite entreprise',
    shortDescription: 'Structurez la gestion financière et administrative de votre petite entreprise.',
    fullDescription: 'Une formation pratique pour organiser la comptabilité simplifiée, le suivi de trésorerie et les bases légales utiles à toute petite entreprise ou activité indépendante en Haïti.',
    categoryId: 'gestion',
    schoolId: 'demo-school-2',
    level: 'Débutant',
    modality: 'in_person',
    commune: 'Port-au-Prince',
    department: 'Ouest',
    duration: { value: 6, unit: 'weeks' },
    schedule: 'Lundi et mercredi, 17h–19h',
    prerequisites: 'Aucun prérequis',
    price: { amount: null, currency: 'HTG', isOnRequest: true },
    registration: { status: 'upcoming', displayLabel: 'Prochaine cohorte à confirmer' },
    capacity: demoCapacity(),
    image: null,
    badge: null,
    publicationStatus: 'published',
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-course-3',
    slug: 'anglais-professionnel',
    title: 'Anglais professionnel',
    shortDescription: 'Gagnez en aisance à l’oral et à l’écrit dans un contexte de travail.',
    fullDescription: 'Ce programme combine des séances en présentiel et des modules en ligne pour progresser en anglais professionnel : communication orale, rédaction d’e-mails et vocabulaire métier.',
    categoryId: 'langues',
    schoolId: 'demo-school-3',
    level: 'Intermédiaire',
    modality: 'hybrid',
    commune: 'Pétion-Ville',
    department: 'Ouest',
    duration: { value: 10, unit: 'weeks' },
    schedule: 'Mardi et jeudi, 18h–20h, avec modules en ligne complémentaires',
    prerequisites: 'Niveau débutant en anglais recommandé',
    price: { amount: 2800, currency: 'HTG', isOnRequest: false },
    registration: { status: 'open', displayLabel: 'Inscriptions ouvertes toute l’année' },
    capacity: demoCapacity(),
    image: null,
    badge: null,
    publicationStatus: 'published',
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-course-4',
    slug: 'soins-infirmiers-auxiliaires',
    title: 'Soins infirmiers auxiliaires',
    shortDescription: 'Préparez-vous aux gestes de base du soin en structure de santé.',
    fullDescription: 'Cette formation couvre les fondamentaux du soin auxiliaire : hygiène, premiers gestes de soin et accompagnement des patients, avec des mises en situation encadrées par l’équipe pédagogique.',
    categoryId: 'sante',
    schoolId: 'demo-school-5',
    level: 'Débutant',
    modality: 'in_person',
    commune: 'Cap-Haïtien',
    department: 'Nord',
    duration: { value: 12, unit: 'months' },
    schedule: 'Du lundi au vendredi, 8h–12h',
    prerequisites: 'Diplôme de fin d’études secondaires recommandé',
    price: { amount: null, currency: 'HTG', isOnRequest: true },
    registration: { status: 'upcoming', displayLabel: 'Prochaine cohorte à confirmer' },
    capacity: demoCapacity(),
    image: null,
    badge: null,
    publicationStatus: 'published',
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-course-5',
    slug: 'electricite-batiment',
    title: 'Électricité bâtiment',
    shortDescription: 'Apprenez les bases de l’installation électrique résidentielle en toute sécurité.',
    fullDescription: 'Une formation pratique aux normes de base de l’électricité bâtiment : lecture de schémas, installation et sécurité sur chantier, avec des sessions encadrées en atelier.',
    categoryId: 'metiers',
    schoolId: 'demo-school-4',
    level: 'Débutant',
    modality: 'in_person',
    commune: 'Delmas',
    department: 'Ouest',
    duration: { value: 4, unit: 'months' },
    schedule: 'Samedi, 9h–15h',
    prerequisites: 'Aucun prérequis',
    price: { amount: 5000, currency: 'HTG', isOnRequest: false },
    registration: { status: 'upcoming', displayLabel: 'Prochaine cohorte à confirmer' },
    capacity: demoCapacity(),
    image: null,
    badge: null,
    publicationStatus: 'published',
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-course-6',
    slug: 'illustration-numerique',
    title: 'Illustration numérique',
    shortDescription: 'Développez votre style et vos techniques d’illustration sur outils numériques.',
    fullDescription: 'Ce parcours en ligne vous accompagne dans l’apprentissage des outils d’illustration numérique, avec des ateliers en direct pour pratiquer, échanger et recevoir des retours réguliers.',
    categoryId: 'arts',
    schoolId: 'demo-school-6',
    level: 'Intermédiaire',
    modality: 'online',
    commune: null,
    department: null,
    duration: { value: 6, unit: 'weeks' },
    schedule: 'Cours en ligne à votre rythme, avec ateliers en direct mensuels',
    prerequisites: 'Notions de base en dessin ou en logiciels graphiques',
    price: { amount: 3200, currency: 'HTG', isOnRequest: false },
    registration: { status: 'open', displayLabel: 'Inscriptions ouvertes toute l’année' },
    capacity: demoCapacity(),
    image: null,
    badge: null,
    publicationStatus: 'published',
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-course-7',
    slug: 'cybersecurite-debutants',
    title: 'Cybersécurité pour débutants',
    shortDescription: 'Comprenez les bases de la sécurité informatique et des bonnes pratiques numériques.',
    fullDescription: 'Cette formation d’introduction présente les menaces informatiques courantes et les bonnes pratiques essentielles pour se protéger, protéger ses données et celles d’une petite structure.',
    categoryId: 'tech',
    schoolId: 'demo-school-1',
    level: 'Débutant',
    modality: 'online',
    commune: null,
    department: null,
    duration: { value: 5, unit: 'weeks' },
    schedule: 'Cours en ligne à votre rythme, 3 modules par semaine',
    prerequisites: 'Aucun prérequis',
    price: { amount: 4000, currency: 'HTG', isOnRequest: false },
    registration: { status: 'open', displayLabel: 'Inscriptions ouvertes toute l’année' },
    capacity: demoCapacity(),
    image: null,
    badge: 'Nouveau',
    publicationStatus: 'published',
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  },
  {
    id: 'demo-course-8',
    slug: 'marketing-digital-pme',
    title: 'Marketing digital pour PME',
    shortDescription: 'Utilisez les réseaux sociaux et les outils numériques pour développer votre activité.',
    fullDescription: 'Une formation concrète pour construire une présence en ligne efficace : réseaux sociaux, contenu et bases de la publicité numérique, adaptée aux petites et moyennes entreprises.',
    categoryId: 'gestion',
    schoolId: 'demo-school-2',
    level: 'Intermédiaire',
    modality: 'hybrid',
    commune: 'Pétion-Ville',
    department: 'Ouest',
    duration: { value: 4, unit: 'weeks' },
    schedule: 'Vendredi soir, en présentiel, avec ressources en ligne',
    prerequisites: 'Notions de base en gestion ou en marketing',
    price: { amount: null, currency: 'HTG', isOnRequest: true },
    registration: { status: 'upcoming', displayLabel: 'Prochaine cohorte à confirmer' },
    capacity: demoCapacity(),
    image: null,
    badge: 'Nouveau',
    publicationStatus: 'published',
    isDemo: true,
    createdAt: DEMO_CREATED_AT,
    updatedAt: DEMO_CREATED_AT,
    publishedAt: DEMO_PUBLISHED_AT
  }
];
