import { billingApi, money, esc } from './logiciel proformat/api-v2.js';
import { auth, authReadyPromise } from './firebase-init.js?v=20260831-4';

const root = document.getElementById('publicDocument'); const token = new URLSearchParams(location.search).get('t') || ''; let proforma;
const notify = (message) => { const el=document.getElementById('publicNotice'); el.textContent=message; el.hidden=false; setTimeout(()=>el.hidden=true,3500); };

function render() {
  const p=proforma; root.innerHTML=`<article class="document"><div class="doc-head"><div><p>PROFORMA</p><h1>${esc(p.number)}</h1><p>${esc(p.provider.businessName)}</p></div><span class="status ${esc(p.status)}">${esc(p.status.replaceAll('_',' '))}</span></div><div class="meta"><div><strong>Prestataire</strong><p>${esc(p.provider.businessName)}</p><p>${esc(p.provider.contactName || '')}</p></div><div><strong>Client</strong><p>${esc(p.client.name)}</p><p>${esc(p.client.company || '')}</p></div><div><strong>Date</strong><p>${esc(p.issueDate)}</p></div><div><strong>Expiration</strong><p>${esc(p.expiryDate)}</p></div></div><div class="items">${p.items.map(i=>`<div class="item"><div><strong>${esc(i.name)}</strong><small>${esc(i.description||'')} · ${i.quantity} × ${money(i.unitPriceMinor)}</small></div><strong>${money(i.lineTotalMinor)}</strong></div>`).join('')}<div class="totals"><div><span>Sous-total</span><strong>${money(p.subtotalMinor)}</strong></div>${p.discountMinor?`<div><span>Réduction</span><strong>− ${money(p.discountMinor)}</strong></div>`:''}${p.taxMinor?`<div><span>Taxes</span><strong>${money(p.taxMinor)}</strong></div>`:''}${p.feeMinor?`<div><span>Frais</span><strong>${money(p.feeMinor)}</strong></div>`:''}<div class="total"><span>Total</span><strong>${money(p.totalMinor)}</strong></div></div></div><div class="doc-actions">${p.status==='PAID'?'<button class="btn primary" disabled>Paiement confirmé</button>':'<button id="payBtn" class="btn primary">Payer avec MonCash</button>'}<button id="pdfBtn" class="btn ghost">Télécharger le PDF</button><button id="shareBtn" class="btn ghost">Partager</button></div><div class="security">Le statut de paiement est vérifié auprès de MonCash par le serveur SmartCut. Une page de succès seule ne constitue jamais une preuve de paiement.</div></article>`;
  document.getElementById('payBtn')?.addEventListener('click', pay); document.getElementById('pdfBtn').addEventListener('click', pdf); document.getElementById('shareBtn').addEventListener('click', share);
}
async function pay(event){const btn=event.currentTarget;await authReadyPromise;if(!auth.currentUser){location.assign(`./index.html?auth=login&returnTo=${encodeURIComponent(location.href)}`);return;}btn.disabled=true;btn.textContent='Connexion à MonCash…';try{const key=crypto.randomUUID();const result=await billingApi('StartPayment',{method:'POST',body:{token,idempotencyKey:key},idempotencyKey:key,user:auth.currentUser});localStorage.setItem('smartcut_billing_payment',JSON.stringify({token,paymentIntentId:result.paymentIntentId}));location.assign(result.checkoutUrl);}catch(e){notify(e.message);btn.disabled=false;btn.textContent='Payer avec MonCash';}}
async function verifyReturn(){const q=new URLSearchParams(location.search);const intent=q.get('paymentIntentId');if(!intent)return;await authReadyPromise;if(!auth.currentUser){location.assign(`./index.html?auth=login&returnTo=${encodeURIComponent(location.href)}`);return;}root.innerHTML='<div class="loading">Vérification réelle du paiement auprès de MonCash…</div>';try{await billingApi('VerifyPayment',{method:'POST',body:{token,paymentIntentId:intent,transactionId:q.get('transactionId')||''},user:auth.currentUser});localStorage.removeItem('smartcut_billing_payment');proforma=(await billingApi('GetPublicProforma',{query:{t:token}})).proforma;render();notify('Paiement confirmé. Votre facture a été créée.');}catch(e){root.innerHTML=`<div class="error"><h1>Confirmation en cours</h1><p>${esc(e.message)}</p><button id="retry" class="btn primary">Vérifier de nouveau</button></div>`;document.getElementById('retry').onclick=verifyReturn;}}
function pdf(){if(!window.jspdf?.jsPDF){notify('Générateur PDF en chargement. Réessayez.');return;}const d=new window.jspdf.jsPDF();d.setFillColor(17,24,39);d.rect(0,0,210,34,'F');d.setTextColor(255);d.setFontSize(19);d.text(proforma.provider.businessName,15,21);d.setTextColor(17,24,39);d.setFontSize(18);d.text('PROFORMA',15,49);d.setFontSize(10);d.text(proforma.number,195,49,{align:'right'});d.text(`Client : ${proforma.client.name}`,15,62);let y=78;proforma.items.forEach(i=>{d.text(`${i.quantity} × ${i.name}`,15,y);d.text(money(i.lineTotalMinor),195,y,{align:'right'});y+=9;});d.line(15,y,195,y);d.setFontSize(15);d.text(`TOTAL : ${money(proforma.totalMinor)}`,195,y+14,{align:'right'});d.save(`${proforma.number}.pdf`);}
async function share(){const payload={title:`Proforma ${proforma.number}`,text:`Proforma ${proforma.number} — ${money(proforma.totalMinor)}`,url:location.href};if(navigator.share)await navigator.share(payload).catch(()=>{});else{await navigator.clipboard.writeText(location.href);notify('Lien copié.');}}

if(!token){root.innerHTML='<div class="error"><h1>Lien incomplet</h1><p>Le jeton sécurisé est absent.</p></div>';}else{try{proforma=(await billingApi('GetPublicProforma',{query:{t:token}})).proforma;if(new URLSearchParams(location.search).has('paymentIntentId'))await verifyReturn();else render();}catch(e){root.innerHTML=`<div class="error"><h1>Document indisponible</h1><p>${esc(e.message)}</p></div>`;}}
