import { auth, db } from './firebase-init.js';
import { onAuthStateChanged, signOut } from 'https://www.gstatic.com/firebasejs/10.7.0/firebase-auth.js';
import { collection, getDocs, query, where, doc, getDoc } from 'https://www.gstatic.com/firebasejs/10.7.0/firebase-firestore.js';
const FN='https://us-central1-smartcutservices-9ce54.cloudfunctions.net/'; const $=s=>document.querySelector(s); const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])); const fmt=d=>new Date(d).toLocaleString('fr-FR',{dateStyle:'medium',timeStyle:'short'});
let user, appointments=[], slots=[]; const notice=(t,e=false)=>{ $('#notice').textContent=t; $('#notice').style.color=e?'#a33a32':'#0d7665'; };
async function call(name,body){const token=await user.getIdToken();const r=await fetch(FN+name,{method:'POST',headers:{Authorization:`Bearer ${token}`,'Content-Type':'application/json'},body:JSON.stringify(body)});const d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.message||'Action impossible');return d;}
async function load(){const profile=await getDoc(doc(db,'clients',user.uid));const data=profile.data()||{};if(data.role!=='doctor'||data.doctorStatus!=='verified')throw Error('L’accès est réservé aux médecins vérifiés.');const p=data.doctorProfile||{};$('#doctorName').textContent=p.professionalName||user.email||'Médecin';$('#profileSummary').innerHTML=`<p><strong>${esc(p.professionalName||'Médecin')}</strong></p><p class="muted">${esc(p.specialty||'Spécialité non renseignée')} · ${esc(p.address||'Adresse non renseignée')}</p><p class="muted">${esc(p.phone||'Téléphone non renseigné')} · Profil vérifié</p>`;const [a,s]=await Promise.all([getDocs(query(collection(db,'healthAppointments'),where('providerUid','==',user.uid))),getDocs(query(collection(db,'healthAvailabilitySlots'),where('providerUid','==',user.uid)))]);appointments=a.docs.map(x=>({id:x.id,...x.data()})).sort((x,y)=>String(x.startsAt||'').localeCompare(String(y.startsAt||'')));slots=s.docs.map(x=>({id:x.id,...x.data()})).filter(x=>x.status==='AVAILABLE').sort((x,y)=>String(x.startsAt).localeCompare(String(y.startsAt)));render();}
function render(){const pending=appointments.filter(x=>['CONFIRMED','DOCTOR_ACCEPTED'].includes(x.status));const todayKey=new Date().toISOString().slice(0,10);const completed=appointments.filter(x=>x.status==='COMPLETED');const patientMap=new Map(appointments.map(x=>[x.patientUid,x]));$('#pending').textContent=pending.length;$('#today').textContent=appointments.filter(x=>String(x.startsAt||'').startsWith(todayKey)).length;$('#patientsCount').textContent=patientMap.size;$('#revenue').textContent=`${completed.reduce((n,x)=>n+Number(x.professionalAmount||x.amount||0),0).toLocaleString('fr-FR')} HTG`;const rows=appointments.length?appointments.map(x=>`<div class="appointment"><div><strong>${esc(x.specialtyName||x.planName||'Consultation')}</strong><br><small class="muted">${esc(fmt(x.startsAt))} · ${esc(x.status)}</small></div><div class="actions">${x.status==='CONFIRMED'?`<button class="btn primary" data-action="DOCTOR_ACCEPTED" data-id="${x.id}">Accepter</button><button class="btn danger" data-action="DOCTOR_REFUSED" data-id="${x.id}">Refuser</button>`:''}${x.status==='DOCTOR_ACCEPTED'?`<button class="btn primary" data-action="IN_PROGRESS" data-id="${x.id}">Démarrer</button><button class="btn" data-action="PATIENT_NO_SHOW" data-id="${x.id}">Absent</button>`:''}${x.status==='IN_PROGRESS'?`<button class="btn primary" data-action="COMPLETED" data-id="${x.id}">Terminer</button>`:''}</div></div>`).join(''):'<div class="empty">Aucune consultation.</div>';$('#appointments').innerHTML=rows;$('#overviewList').innerHTML=rows;$('#slots').innerHTML=slots.length?slots.slice(0,8).map(x=>`<div class="slot"><span>${esc(fmt(x.startsAt))}</span><span class="badge">Disponible</span></div>`).join(''):'<div class="empty">Aucun créneau.</div>';$('#patientsList').innerHTML=patientMap.size?[...patientMap.entries()].map(([id,x])=>`<div class="patient"><div><strong>Patient ${esc(id.slice(0,8))}</strong><br><small class="muted">Dernière consultation : ${esc(fmt(x.startsAt))}</small></div><span class="badge">${esc(x.status)}</span></div>`).join(''):'<div class="empty">Aucun patient.</div>';$('#walletSummary').innerHTML=`<p><strong>${completed.length}</strong> consultation(s) terminée(s)</p><p><strong>${esc($('#revenue').textContent)}</strong> estimés après validation des présences.</p>`;}
$('#slotForm').addEventListener('submit',async e=>{e.preventDefault();try{await call('healthSaveAvailability',{type:'doctor',startsAt:new Date($('#startsAt').value).toISOString(),endsAt:new Date($('#endsAt').value).toISOString()});notice('Créneau publié.');e.target.reset();await load();}catch(x){notice(x.message,true);}});
document.querySelectorAll('[data-tab]').forEach(b=>b.onclick=()=>{document.querySelectorAll('.panel').forEach(p=>p.hidden=p.id!==b.dataset.tab);document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===b));});
document.addEventListener('click',async e=>{const b=e.target.closest('[data-action]');if(!b)return;try{await call('healthDoctorUpdateConsultation',{appointmentId:b.dataset.id,status:b.dataset.action});notice('Consultation mise à jour.');await load();}catch(x){notice(x.message,true);}}); $('#logout').onclick=()=>signOut(auth);
onAuthStateChanged(auth,async u=>{if(!u){notice('Connectez-vous pour ouvrir votre espace médecin.',true);return;}user=u;try{await load();}catch(e){notice(e.message,true);}});
