const PROJECT_ID='smartcutservices-9ce54';
const FUNCTION_BASE_URL=`https://us-central1-${PROJECT_ID}.cloudfunctions.net`;
const root=document.getElementById('payment-content');
const escapeHtml=value=>String(value??'').replace(/[&<>"']/g,char=>({ '&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;' }[char]));
const money=value=>new Intl.NumberFormat('fr-HT',{style:'currency',currency:'HTG',minimumFractionDigits:0,maximumFractionDigits:0}).format(Number(value||0));
async function request(path,options={}){const response=await fetch(`${FUNCTION_BASE_URL}/${path}`,{headers:{Accept:'application/json',...(options.body?{'Content-Type':'application/json'}:{})},...options});const payload=await response.json().catch(()=>({}));if(!response.ok||payload?.ok===false)throw new Error(payload?.message||'Ce lien de paiement est indisponible.');return payload;}
function unavailable(){root.className='payment-unavailable';root.innerHTML='<p class="payment-eyebrow">Lien indisponible</p><h1>Ce paiement n’est plus disponible.</h1><p>Le lien a peut-être expiré ou été désactivé. Contactez la personne qui vous l’a envoyé.</p>';}
async function init(){const reference=new URLSearchParams(location.search).get('ref');if(!reference){unavailable();return;}let link;try{link=(await request(`getPaymentLink?ref=${encodeURIComponent(reference)}`)).link;}catch(_){unavailable();return;}root.className='';root.innerHTML=`<p class="payment-eyebrow">Paiement Smart Cut</p><h1>Finalisez votre paiement.</h1><p class="payment-description">${escapeHtml(link.description)}</p><div class="amount-box"><span>Montant à régler</span><strong>${money(link.amount)}</strong></div><form class="payment-form" id="payment-form"><label>Nom complet<input name="payerName" autocomplete="name" required minlength="2" maxlength="160" placeholder="Votre nom complet"></label><label>Téléphone<input name="payerPhone" autocomplete="tel" inputmode="tel" required minlength="6" maxlength="40" placeholder="Ex. 37 00 00 00"></label><button class="pay-button" type="submit">Payer ${money(link.amount)} avec MonCash <span aria-hidden="true">→</span></button><p class="payment-note">En continuant, vous serez redirigé vers la page sécurisée MonCash.</p></form><div class="payment-error" id="payment-error" hidden></div>`;root.querySelector('#payment-form').addEventListener('submit',async event=>{event.preventDefault();const form=event.currentTarget;const button=form.querySelector('button');const error=root.querySelector('#payment-error');button.disabled=true;button.textContent='Ouverture de MonCash…';error.hidden=true;try{const data=new FormData(form);const out=await request('startPaymentLinkPayment',{method:'POST',body:JSON.stringify({reference,payerName:data.get('payerName'),payerPhone:data.get('payerPhone')})});location.assign(out.checkoutUrl);}catch(cause){error.textContent=cause.message||'Impossible de démarrer le paiement.';error.hidden=false;button.disabled=false;button.innerHTML=`Payer ${money(link.amount)} avec MonCash <span aria-hidden="true">→</span>`;}});}
init();
