import { auth, authReadyPromise } from '../../firebase-init.js?v=20260523-6';
import { marketplaceApi } from '../../marketplace-api.js';
import { esc, badge, money } from './ui.js';

const root=document.getElementById('moderationContent'),dialog=document.getElementById('moderationDialog'),body=document.getElementById('moderationDialogBody');let data;
function render(){const profiles=Object.fromEntries(data.profiles.map(x=>[x.id,x]));root.innerHTML=`<div class="panel-head"><div><h2>Profils en attente</h2><p>Identité et informations publiques.</p></div>${badge('PENDING_REVIEW')}</div>${data.pendingProfiles?.length?data.pendingProfiles.map(p=>`<article class="activity"><div><strong>${esc(p.businessName)}</strong><span>${esc(p.professionalTitle)}</span></div><div class="row-actions"><button class="button primary" data-profile-action="APPROVE" data-id="${p.id}">Approuver</button><button class="button" data-profile-action="REJECT" data-id="${p.id}">Rejeter</button></div></article>`).join(''):'<p>Aucun profil en attente.</p>'}<div class="panel-head" style="margin-top:32px"><div><h2>Services en attente</h2><p>Chaque décision est journalisée.</p></div>${badge('PENDING_REVIEW')}</div>${data.services.length?data.services.map(s=>`<article class="activity"><div><strong>${esc(s.name)}</strong><span>${esc(profiles[s.ownerUid]?.businessName||s.ownerUid)} · ${s.pricingType==='CUSTOM_QUOTE'?'Sur devis':money(s.priceMinor)}</span></div><div class="row-actions"><button class="button primary" data-action="APPROVE" data-id="${s.id}">Approuver</button><button class="button" data-action="REJECT" data-id="${s.id}">Rejeter</button></div></article>`).join(''):'<p>Aucun service en attente.</p>'}<div class="panel-head" style="margin-top:32px"><div><h2>Litiges ouverts</h2><p>Résolution manuelle et référence financière obligatoires.</p></div></div>${data.openDisputes?.length?data.openDisputes.map(d=>`<article class="activity"><div><strong>${esc(d.reason||'Litige')}</strong><span>${esc(d.explanation)}</span></div><div class="row-actions"><button class="button" data-dispute-action="RESOLVE_PROVIDER" data-id="${d.id}">Résoudre pour le prestataire</button><button class="button" data-dispute-action="FULL_REFUND" data-id="${d.id}">Remboursement intégral</button></div></article>`).join(''):'<p>Aucun litige ouvert.</p>'}`;}
document.addEventListener('click',async e=>{const t=e.target.closest('[data-action],[data-profile-action],[data-dispute-action]');if(!t)return;if(t.dataset.disputeAction){const refund=t.dataset.disputeAction==='FULL_REFUND';body.innerHTML=`<div class="dialog-head"><h2>Résoudre le litige</h2><button class="icon-button" id="close">×</button></div><form id="disputeResolutionForm"><input type="hidden" name="id" value="${t.dataset.id}"><input type="hidden" name="action" value="${t.dataset.disputeAction}"><label>Décision<textarea name="resolution" required></textarea></label>${refund?'<label>Référence du remboursement effectué<input name="refundReference" required></label>':''}<button class="button primary">Enregistrer la décision</button></form>`;dialog.showModal();document.getElementById('close').onclick=()=>dialog.close();return;}if(t.dataset.profileAction){try{await marketplaceApi('ModerateProfile',{method:'POST',requireAuth:true,body:{uid:t.dataset.id,action:t.dataset.profileAction}});show('Profil mis à jour.');await load();}catch(err){show(err.message,true);}return;}if(t.dataset.action==='REJECT'){body.innerHTML=`<div class="dialog-head"><h2>Motif du rejet</h2><button class="icon-button" id="close">×</button></div><form id="rejectForm"><input type="hidden" name="id" value="${t.dataset.id}"><label>Motif<textarea name="reason" required></textarea></label><button class="button primary">Confirmer le rejet</button></form>`;dialog.showModal();document.getElementById('close').onclick=()=>dialog.close();return;}try{await decide(t.dataset.id,t.dataset.action,'');}catch(err){show(err.message,true);}});
document.addEventListener('submit',async e=>{if(!['rejectForm','disputeResolutionForm'].includes(e.target.id))return;e.preventDefault();const b=Object.fromEntries(new FormData(e.target));try{if(e.target.id==='rejectForm')await decide(b.id,'REJECT',b.reason);else{await marketplaceApi('ResolveDispute',{method:'POST',requireAuth:true,body:b});show('Décision enregistrée.');await load();}dialog.close();}catch(err){show(err.message,true);}});
async function decide(id,action,reason){await marketplaceApi('ModerateService',{method:'POST',requireAuth:true,body:{id,action,reason}});show('Décision enregistrée.');await load();}
function show(message,error=false){const n=document.getElementById('notice');n.textContent=message;n.className=`notice ${error?'error':''}`;n.hidden=false;setTimeout(()=>n.hidden=true,4000);}
async function load(){try{data=await marketplaceApi('ModerationQueue',{requireAuth:true});render();}catch(e){root.innerHTML=`<div class="empty"><h2>Accès indisponible</h2><p>${esc(e.message)}</p></div>`;}}
await authReadyPromise;if(!auth.currentUser)location.assign('../index.html?auth=login');else load();
