import { openDialog, openPromptDialog } from '../shared/dialog.js';

export async function renderStudentsView(container, context) {
  container.innerHTML = `<section><div class="sst-course-view-heading"><div><span class="sst-app-kicker">Apprenants</span><h1>Suivi des apprenants</h1><p>Les informations affichées proviennent des inscriptions enregistrées.</p></div><button class="sst-btn sst-btn-secondary" data-export disabled><i class="fas fa-file-csv"></i> Exporter CSV</button></div><div class="sst-loading">Chargement…</div></section>`;
  try {
    const result = await context.api.enrollments(context.organization.id, context.state.course.id);
    const rows = result.enrollments || [];
    const canManage = ['creator_owner','creator_manager'].includes(context.organization.myRole);
    container.innerHTML = `<section class="sst-students-page"><div class="sst-course-view-heading"><div><span class="sst-app-kicker">Apprenants</span><h1>Suivi des apprenants</h1><p>${rows.length} inscription${rows.length === 1 ? '' : 's'} enregistrée${rows.length === 1 ? '' : 's'}.</p></div><div>${canManage ? '<button class="sst-btn sst-btn-primary" data-toggle-grant><i class="fas fa-user-plus"></i> Accorder un accès</button>' : ''}<button class="sst-btn sst-btn-secondary" data-export ${canManage && rows.length ? '' : 'disabled'}><i class="fas fa-file-csv"></i> Exporter CSV</button></div></div>
      ${canManage ? `<form class="sst-course-panel sst-manual-grant" data-grant-form hidden><h2>Accès manuel</h2><p>Utilisez l’UID Firebase du compte apprenant. L’email seul n’est jamais accepté comme preuve d’identité.</p><div class="sst-course-form-grid"><label>UID Firebase *<input class="sst-input" name="studentUid" required></label><label>Email *<input class="sst-input" type="email" name="studentEmail" required></label><label>Nom<input class="sst-input" name="studentName"></label></div><button class="sst-btn sst-btn-primary">Accorder l’accès</button></form>` : ''}
      <div class="sst-student-filters"><label><i class="fas fa-magnifying-glass"></i><input class="sst-input" data-student-search placeholder="Rechercher un nom ou un email"></label><select class="sst-select" data-student-status><option value="">Tous les statuts</option><option value="confirmed">Confirmé</option><option value="pending_payment">Paiement en attente</option><option value="suspended">Suspendu</option></select></div>
      <div data-student-table></div></section>`;
    const render = () => {
      const term = container.querySelector('[data-student-search]').value.trim().toLowerCase(); const status = container.querySelector('[data-student-status]').value;
      const filtered = rows.filter((row) => (!status || row.status === status) && (!term || `${row.studentName || ''} ${row.studentEmail || ''}`.toLowerCase().includes(term)));
      container.querySelector('[data-student-table]').innerHTML = filtered.length ? `<div class="sst-table-wrap"><table class="sst-table"><thead><tr><th>Apprenant</th><th>Inscription</th><th>Paiement</th><th>Progression</th><th>Dernière activité</th>${canManage ? '<th>Accès</th>' : ''}</tr></thead><tbody>${filtered.map((row) => `<tr><td><strong>${context.escapeHtml(row.studentName || 'Sans nom')}</strong><small>${context.escapeHtml(row.studentEmail || '')}</small></td><td><span class="sst-badge ${context.escapeHtml(row.status)}">${context.escapeHtml(statusLabel(row.status))}</span></td><td>${context.formatCurrency(row.amountDue || 0)}</td><td><progress max="100" value="${Number(row.completionPercentage) || 0}"></progress><small>${Number(row.completionPercentage) || 0}%</small></td><td>${formatTimestamp(row.lastAccessedAt || row.updatedAt || row.createdAt)}</td>${canManage ? `<td><div class="sst-lesson-actions"><button data-access-action="${row.status === 'suspended' ? 'restore' : 'suspend'}" data-enrollment-id="${context.escapeHtml(row.id)}" title="${row.status === 'suspended' ? 'Rétablir' : 'Suspendre'}"><i class="fas ${row.status === 'suspended' ? 'fa-unlock' : 'fa-pause'}"></i></button><button data-access-action="extend" data-enrollment-id="${context.escapeHtml(row.id)}" title="Prolonger de 30 jours"><i class="fas fa-calendar-plus"></i></button></div></td>` : ''}</tr>`).join('')}</tbody></table></div>` : '<div class="sst-course-empty-inline">Aucun apprenant ne correspond à ces filtres.</div>';
      container.querySelectorAll('.sst-lesson-actions').forEach((actions, index) => actions.insertAdjacentHTML('beforeend', `<button data-add-note="${context.escapeHtml(filtered[index].id)}" title="Note interne"><i class="fas fa-note-sticky"></i></button>`));
      container.querySelectorAll('[data-access-action]').forEach((button) => button.addEventListener('click', async () => {
        const action = button.dataset.accessAction;
        const label = action === 'suspend' ? 'Suspendre cet accès' : action === 'restore' ? 'Rétablir cet accès' : 'Prolonger cet accès de 30 jours';
        if (!await openDialog({ title: `${label} ?`, message: 'L’action sera appliquée côté serveur et ajoutée au journal d’audit.', confirmLabel: label, danger: action === 'suspend' })) return;
        try { await context.api.manageEnrollment({ organizationId: context.organization.id, enrollmentId: button.dataset.enrollmentId, action, ...(action === 'extend' ? { days: 30 } : {}) }); context.toast('Accès apprenant mis à jour.'); await renderStudentsView(container, context); } catch (error) { context.toast(error.message, 'error'); }
      }));
      container.querySelectorAll('[data-add-note]').forEach((button) => button.addEventListener('click', async () => { const note = await openPromptDialog({ title: 'Note interne', label: 'Note visible uniquement par l’équipe', confirmLabel: 'Enregistrer' }); if (note === null) return; try { await context.api.manageEnrollment({ organizationId: context.organization.id, enrollmentId: button.dataset.addNote, action: 'note', note }); context.toast('Note interne enregistrée.'); } catch (error) { context.toast(error.message, 'error'); } }));
    };
    container.querySelector('[data-student-search]').addEventListener('input', render); container.querySelector('[data-student-status]').addEventListener('change', render); render();
    container.querySelector('[data-toggle-grant]')?.addEventListener('click', () => { const form = container.querySelector('[data-grant-form]'); form.hidden = !form.hidden; if (!form.hidden) form.querySelector('input').focus(); });
    container.querySelector('[data-grant-form]')?.addEventListener('submit', async (event) => { event.preventDefault(); const values = new FormData(event.currentTarget); try { await context.api.manageEnrollment({ organizationId: context.organization.id, courseId: context.state.course.id, action: 'grant', studentUid: values.get('studentUid'), studentEmail: values.get('studentEmail'), studentName: values.get('studentName') }); context.toast('Accès manuel accordé.'); await renderStudentsView(container, context); } catch (error) { context.toast(error.message, 'error'); } });
    container.querySelector('[data-export]').addEventListener('click', async () => {
      if (!await openDialog({ title: 'Exporter les données apprenants ?', message: 'Le fichier contient des noms, emails, statuts de paiement et progressions. Conservez-le dans un emplacement sécurisé.', confirmLabel: 'Créer le CSV' })) return;
      const header = ['Nom','Email','Statut','Montant HTG','Progression']; const lines = [header, ...rows.map((row) => [row.studentName || '', row.studentEmail || '', row.status || '', row.amountDue || 0, row.completionPercentage || 0])];
      const csv = lines.map((line) => line.map((value) => `"${String(value).replace(/"/g, '""')}"`).join(',')).join('\r\n'); const url = URL.createObjectURL(new Blob([csv], { type: 'text/csv;charset=utf-8' })); const link = document.createElement('a'); link.href = url; link.download = `apprenants-${context.state.course.slug || context.state.course.id}.csv`; link.click(); URL.revokeObjectURL(url);
      context.toast('Export CSV créé.');
    });
  } catch (error) { container.innerHTML = `<div class="sst-error">${context.escapeHtml(error.message)}</div>`; }
}

function statusLabel(status) { return ({ confirmed: 'Confirmé', pending_payment: 'En attente', suspended: 'Suspendu', refunded: 'Remboursé' })[status] || status || 'Inconnu'; }
function formatTimestamp(value) { const date = value?.toDate?.() || (value?._seconds ? new Date(value._seconds * 1000) : null); return date && !Number.isNaN(date.getTime()) ? date.toLocaleDateString('fr-FR') : 'Aucune activité'; }
